# Generated by Django 3.0.5 on 2020-06-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200615_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
