# Generated by Django 3.0.5 on 2020-06-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_mce_text2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mce',
        ),
    ]
