# Generated by Django 3.0.5 on 2020-06-12 09:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_mce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
