# Generated by Django 3.0.5 on 2020-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200428_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
                ('subtext', models.TextField()),
            ],
        ),
    ]
