# Generated by Django 3.0.5 on 2020-06-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200622_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновой вариант'), ('published', 'Опубликован')], default='draft', max_length=20, null=True),
        ),
    ]
