# Generated by Django 3.0.5 on 2020-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200617_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
