# Generated by Django 3.0.5 on 2020-06-12 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_mce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='subtext',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mce',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
