# Generated by Django 3.0.5 on 2020-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200528_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtext',
            field=models.TextField(default='anna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
    ]
