# Generated by Django 3.0.5 on 2020-06-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200612_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecontent',
            options={'ordering': ('id',), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьй'},
        ),
    ]
