# Generated by Django 3.0.5 on 2020-05-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200528_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtext',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
                ('subtext', models.TextField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='pages.Post')),
            ],
        ),
    ]
