# Generated by Django 3.0.5 on 2020-05-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_articlecontent_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='pages.Post'),
            preserve_default=False,
        ),
    ]
