# Generated by Django 3.0.5 on 2020-05-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
