# Generated by Django 3.0.5 on 2020-05-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='pages.Post'),
        ),
    ]
