# Generated by Django 3.0.5 on 2020-06-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200614_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
