# Generated by Django 3.0.5 on 2020-06-01 21:37

import ckeditor.fields
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pages', '0014_articleimage_articletext_articletitle_artilcecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletext',
            name='post',
        ),
        migrations.RemoveField(
            model_name='articletitle',
            name='post',
        ),
        migrations.RemoveField(
            model_name='artilcecode',
            name='post',
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='subtext',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='ArticleText',
        ),
        migrations.DeleteModel(
            name='ArticleTitle',
        ),
        migrations.DeleteModel(
            name='ArtilceCode',
        ),
    ]
