# Generated by Django 3.0.5 on 2020-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
