# Generated by Django 3.0.5 on 2020-06-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200608_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категорий'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьй'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
