# Generated by Django 3.0.5 on 2020-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200609_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='pages.Post'),
        ),
    ]
